name: Release

on:
  push:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-node@v4
      - uses: extractions/setup-just@v2
      - run: just dep
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      # - uses: pypa/gh-action-pypi-publish@release/v1
